name: Deply to Github pages
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
      with:
        persist-credentials: false
    - uses: lix-pm/setup-lix@master
    - uses: HaxeFlixel/setup-flixel@master
      with:
        haxe-version: stable
        flixel-versions: release
        target: html5
    - name: Build
      run: npx lix lime build html5 -final
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: ./export/html5/bin
        force_orphan: true
      if: github.ref == 'refs/heads/master'